name: Dart

on:
  push:
    branches: [ "flutterflow" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build Flutter Web
        run: flutter build web --release --base-href "/"

      - name: Deploy to Pages repository
        run: |
          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/sergiogar6/sergiogar6.github.io pages-repo
          rm -r pages-repo/*
          cp -r build/web/* pages-repo/
          cd pages-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Flutter Web"
          git push      
